
#Q1: Which vendors have the most trips, and what is the total revenue generated by that vendor?

import sys
vender_1=0
vender_2=0
for line in sys.stdin:
    line = line.strip()
    vendor, charge = line.split("\t")

    if vendor==1:
        vender_1=vender_1+float(charge)
    else:
        vender_2=vender_2+float(charge)

if vender_1>vender_2:
    print("vender_1="+str(vender_1))
else:
    print("vender_2="+str(vender_2))

