
#Q1: Which vendors have the most trips, and what is the total revenue generated by that vendor?

import sys
import errno

try:
    for line in sys.stdin:
        line = line.strip()
        line = line.split(",")

        if line[0] != "VendorID" and line[0] != "":
            vendor=str(line[0])
            charge=str(line[16])
            print ('%s\t%s' % (vendor, charge))

except IOError as e:
    if e.errno == errno.EPIPE:
        pass